controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
webhook_fedapay:
    path: /webhook
    controller: App\Controller\FedaPayWebhookController::handle
    methods: [POST]
